apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-configmap
  labels:
    app: {{ .Release.Name}}-configmap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  name: "Pallav"
  dob: "30-08-2022"
 
