apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-secret
  labels:
    app: {{ .Release.Name}}-secret
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ b64enc "paas_word" }}
